-- Advertising / Media domain (WPP-style) - DDL

USE DATABASE SNOWFLOW_DEMO;
USE SCHEMA AD_MEDIA;

CREATE OR REPLACE TABLE DIM_ADVERTISER (
  ADVERTISER_ID NUMBER,
  ADVERTISER_NAME STRING,
  INDUSTRY STRING,
  HQ_REGION STRING,
  ACCOUNT_TIER STRING
);

CREATE OR REPLACE TABLE DIM_CAMPAIGN (
  CAMPAIGN_ID NUMBER,
  ADVERTISER_ID NUMBER,
  CAMPAIGN_NAME STRING,
  OBJECTIVE STRING,
  START_DATE DATE,
  END_DATE DATE,
  BUDGET_GBP NUMBER(12,2)
);

CREATE OR REPLACE TABLE DIM_CHANNEL (
  CHANNEL_ID NUMBER,
  CHANNEL_NAME STRING,
  CHANNEL_TYPE STRING
);

CREATE OR REPLACE TABLE DIM_CREATIVE (
  CREATIVE_ID NUMBER,
  CREATIVE_NAME STRING,
  FORMAT STRING,
  MESSAGE_ANGLE STRING
);

CREATE OR REPLACE TABLE DIM_GEO (
  GEO_ID NUMBER,
  GEO_REGION STRING,
  COUNTRY STRING
);

CREATE OR REPLACE TABLE DIM_AUDIENCE (
  AUDIENCE_ID NUMBER,
  AUDIENCE_SEGMENT STRING,
  AUDIENCE_TYPE STRING
);

CREATE OR REPLACE TABLE FACT_AD_PERFORMANCE (
  EVENT_DATE DATE,
  ADVERTISER_ID NUMBER,
  CAMPAIGN_ID NUMBER,
  CHANNEL_ID NUMBER,
  CREATIVE_ID NUMBER,
  GEO_ID NUMBER,
  AUDIENCE_ID NUMBER,
  IMPRESSIONS NUMBER,
  CLICKS NUMBER,
  CONVERSIONS NUMBER,
  VIDEO_VIEWS NUMBER,
  SPEND_GBP NUMBER(12,2),
  REVENUE_GBP NUMBER(12,2)
);
