-- Advertising / Media domain - denormalized view for semantic modeling (Analyst-friendly)

USE DATABASE SNOWFLOW_DEMO;
USE SCHEMA AD_MEDIA;

CREATE OR REPLACE VIEW VW_AD_PERFORMANCE AS
SELECT
  f.EVENT_DATE,
  a.ADVERTISER_NAME,
  a.INDUSTRY,
  a.HQ_REGION,
  a.ACCOUNT_TIER,
  c.CAMPAIGN_NAME,
  c.OBJECTIVE,
  c.BUDGET_GBP,
  ch.CHANNEL_NAME,
  ch.CHANNEL_TYPE,
  cr.CREATIVE_NAME,
  cr.FORMAT AS CREATIVE_FORMAT,
  cr.MESSAGE_ANGLE,
  g.GEO_REGION,
  au.AUDIENCE_SEGMENT,
  au.AUDIENCE_TYPE,
  f.IMPRESSIONS,
  f.CLICKS,
  f.CONVERSIONS,
  f.VIDEO_VIEWS,
  f.SPEND_GBP,
  f.REVENUE_GBP,
  ROUND(f.CLICKS / NULLIF(f.IMPRESSIONS, 0), 6) AS CTR,
  ROUND(f.SPEND_GBP / NULLIF(f.CLICKS, 0), 4) AS CPC_GBP,
  ROUND((f.SPEND_GBP / NULLIF(f.IMPRESSIONS, 0)) * 1000, 4) AS CPM_GBP,
  ROUND(f.SPEND_GBP / NULLIF(f.CONVERSIONS, 0), 4) AS CPA_GBP,
  ROUND(f.REVENUE_GBP / NULLIF(f.SPEND_GBP, 0), 4) AS ROAS
FROM FACT_AD_PERFORMANCE f
JOIN DIM_ADVERTISER a ON f.ADVERTISER_ID = a.ADVERTISER_ID
JOIN DIM_CAMPAIGN c ON f.CAMPAIGN_ID = c.CAMPAIGN_ID
JOIN DIM_CHANNEL ch ON f.CHANNEL_ID = ch.CHANNEL_ID
JOIN DIM_CREATIVE cr ON f.CREATIVE_ID = cr.CREATIVE_ID
JOIN DIM_GEO g ON f.GEO_ID = g.GEO_ID
JOIN DIM_AUDIENCE au ON f.AUDIENCE_ID = au.AUDIENCE_ID;

-- Daily KPIs (quick exec demos)
CREATE OR REPLACE VIEW VW_AD_DAILY_KPIS AS
SELECT
  EVENT_DATE,
  INDUSTRY,
  CHANNEL_TYPE,
  SUM(IMPRESSIONS) AS IMPRESSIONS,
  SUM(CLICKS) AS CLICKS,
  SUM(CONVERSIONS) AS CONVERSIONS,
  SUM(SPEND_GBP) AS SPEND_GBP,
  SUM(REVENUE_GBP) AS REVENUE_GBP,
  ROUND(SUM(CLICKS) / NULLIF(SUM(IMPRESSIONS), 0), 6) AS CTR,
  ROUND(SUM(SPEND_GBP) / NULLIF(SUM(CLICKS), 0), 4) AS CPC_GBP,
  ROUND((SUM(SPEND_GBP) / NULLIF(SUM(IMPRESSIONS), 0)) * 1000, 4) AS CPM_GBP,
  ROUND(SUM(SPEND_GBP) / NULLIF(SUM(CONVERSIONS), 0), 4) AS CPA_GBP,
  ROUND(SUM(REVENUE_GBP) / NULLIF(SUM(SPEND_GBP), 0), 4) AS ROAS
FROM VW_AD_PERFORMANCE
GROUP BY 1,2,3;

