-- Retail domain (Sainsbury’s-style) - DDL
-- Realistic-ish star schema: store/product/customer/promo/channel + sales lines + inventory snapshots.

USE DATABASE SNOWFLOW_DEMO;
USE SCHEMA RETAIL;

CREATE OR REPLACE TABLE DIM_STORE (
  STORE_ID NUMBER,
  STORE_NAME STRING,
  CITY STRING,
  REGION STRING,
  COUNTRY STRING,
  STORE_FORMAT STRING,
  FLOORSPACE_SQM NUMBER(10,2),
  HAS_FUEL_STATION BOOLEAN,
  OPENED_DATE DATE
);

CREATE OR REPLACE TABLE DIM_PRODUCT (
  PRODUCT_ID NUMBER,
  PRODUCT_NAME STRING,
  DEPARTMENT STRING,
  CATEGORY STRING,
  SUBCATEGORY STRING,
  BRAND STRING,
  IS_OWN_BRAND BOOLEAN,
  UNIT_COST NUMBER(10,2),
  LIST_PRICE NUMBER(10,2),
  PACKAGE_SIZE STRING,
  IS_PERISHABLE BOOLEAN
);

CREATE OR REPLACE TABLE DIM_CUSTOMER (
  CUSTOMER_ID NUMBER,
  SEGMENT STRING,
  LOYALTY_TIER STRING,
  AGE_BAND STRING,
  HOUSEHOLD_SIZE NUMBER,
  POSTCODE_AREA STRING,
  SIGNUP_DATE DATE,
  IS_ONLINE_ONLY BOOLEAN
);

CREATE OR REPLACE TABLE DIM_PROMOTION (
  PROMOTION_ID NUMBER,
  PROMOTION_NAME STRING,
  PROMOTION_TYPE STRING,
  DISCOUNT_PCT NUMBER(5,4),
  START_DATE DATE,
  END_DATE DATE
);

CREATE OR REPLACE TABLE DIM_CHANNEL (
  CHANNEL_ID NUMBER,
  CHANNEL_NAME STRING,
  CHANNEL_TYPE STRING
);

CREATE OR REPLACE TABLE FACT_SALES_LINE (
  SALES_LINE_ID NUMBER,
  ORDER_ID NUMBER,
  SALE_TS TIMESTAMP_NTZ,
  SALE_DATE DATE,
  STORE_ID NUMBER,
  CHANNEL_ID NUMBER,
  CUSTOMER_ID NUMBER,
  PRODUCT_ID NUMBER,
  PROMOTION_ID NUMBER,
  QUANTITY NUMBER,
  GROSS_REVENUE NUMBER(12,2),
  DISCOUNT_AMOUNT NUMBER(12,2),
  NET_REVENUE NUMBER(12,2),
  UNIT_COST_TOTAL NUMBER(12,2),
  MARGIN_AMOUNT NUMBER(12,2)
);

CREATE OR REPLACE TABLE FACT_INVENTORY_DAILY (
  SNAPSHOT_DATE DATE,
  STORE_ID NUMBER,
  PRODUCT_ID NUMBER,
  STOCK_ON_HAND NUMBER,
  STOCK_IN_TRANSIT NUMBER,
  REORDER_POINT NUMBER,
  LEAD_TIME_DAYS NUMBER
);
