-- Retail domain - denormalized view for semantic modeling (Analyst-friendly)

USE DATABASE SNOWFLOW_DEMO;
USE SCHEMA RETAIL;

CREATE OR REPLACE VIEW VW_RETAIL_SALES AS
SELECT
  f.SALES_LINE_ID,
  f.ORDER_ID,
  f.CUSTOMER_ID,
  f.STORE_ID,
  f.PRODUCT_ID,
  f.SALE_TS,
  f.SALE_DATE,
  s.REGION,
  s.CITY,
  s.STORE_NAME,
  s.STORE_FORMAT,
  ch.CHANNEL_NAME,
  ch.CHANNEL_TYPE,
  p.DEPARTMENT AS PRODUCT_DEPARTMENT,
  p.CATEGORY AS PRODUCT_CATEGORY,
  p.SUBCATEGORY AS PRODUCT_SUBCATEGORY,
  p.BRAND AS PRODUCT_BRAND,
  p.IS_OWN_BRAND,
  p.PRODUCT_NAME,
  c.SEGMENT AS CUSTOMER_SEGMENT,
  c.LOYALTY_TIER,
  c.AGE_BAND,
  c.HOUSEHOLD_SIZE,
  c.POSTCODE_AREA,
  pr.PROMOTION_NAME,
  pr.PROMOTION_TYPE,
  COALESCE(pr.DISCOUNT_PCT, 0) AS DISCOUNT_PCT,
  f.QUANTITY,
  f.GROSS_REVENUE,
  f.DISCOUNT_AMOUNT,
  f.NET_REVENUE,
  f.UNIT_COST_TOTAL,
  f.MARGIN_AMOUNT,
  ROUND(f.MARGIN_AMOUNT / NULLIF(f.NET_REVENUE, 0), 4) AS MARGIN_PCT
FROM FACT_SALES_LINE f
JOIN DIM_STORE s ON f.STORE_ID = s.STORE_ID
JOIN DIM_CHANNEL ch ON f.CHANNEL_ID = ch.CHANNEL_ID
JOIN DIM_PRODUCT p ON f.PRODUCT_ID = p.PRODUCT_ID
JOIN DIM_CUSTOMER c ON f.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN DIM_PROMOTION pr ON f.PROMOTION_ID = pr.PROMOTION_ID;

-- Inventory risk view (ops-style)
CREATE OR REPLACE VIEW VW_RETAIL_INVENTORY_RISK AS
SELECT
  i.SNAPSHOT_DATE,
  s.REGION,
  s.CITY,
  s.STORE_NAME,
  s.STORE_FORMAT,
  p.PRODUCT_ID,
  p.PRODUCT_NAME,
  p.CATEGORY AS PRODUCT_CATEGORY,
  p.IS_PERISHABLE,
  i.STOCK_ON_HAND,
  i.STOCK_IN_TRANSIT,
  i.REORDER_POINT,
  i.LEAD_TIME_DAYS,
  CASE
    WHEN i.STOCK_ON_HAND <= i.REORDER_POINT THEN 'REORDER'
    WHEN i.STOCK_ON_HAND <= (i.REORDER_POINT * 1.2) THEN 'WATCH'
    ELSE 'OK'
  END AS STOCK_STATUS
FROM FACT_INVENTORY_DAILY i
JOIN DIM_STORE s ON i.STORE_ID = s.STORE_ID
JOIN DIM_PRODUCT p ON i.PRODUCT_ID = p.PRODUCT_ID;

-- Daily KPIs (handy for quick exec demos)
CREATE OR REPLACE VIEW VW_RETAIL_DAILY_KPIS AS
SELECT
  SALE_DATE,
  REGION,
  CHANNEL_TYPE,
  SUM(NET_REVENUE) AS NET_REVENUE,
  SUM(GROSS_REVENUE) AS GROSS_REVENUE,
  SUM(DISCOUNT_AMOUNT) AS DISCOUNT_AMOUNT,
  SUM(MARGIN_AMOUNT) AS MARGIN_AMOUNT,
  COUNT(DISTINCT ORDER_ID) AS ORDERS,
  COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMERS,
  SUM(QUANTITY) AS UNITS,
  ROUND(SUM(NET_REVENUE) / NULLIF(COUNT(DISTINCT ORDER_ID), 0), 2) AS AOV,
  ROUND(SUM(MARGIN_AMOUNT) / NULLIF(SUM(NET_REVENUE), 0), 4) AS MARGIN_PCT
FROM VW_RETAIL_SALES
GROUP BY 1,2,3;

